wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/8_2_4.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/8_2_7.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/58_2_1.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/58_2_2.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/58_2_3.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/58_2_5.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/58_2_6.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/58_2_8.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/58_2_Contents.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/58_3_1.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/58_3_10.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/58_3_2.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/58_3_3.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/58_3_4.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/58_3_5.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/58_3_6.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/58_3_7.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/58_3_8.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/58_3_9.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_1_14_MRoy.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_1_15_SPRaychaudhuri.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_1_16_MSShukla.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_1_1_CDwarkanath.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_1_2_PJDeshpande.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_1_3_LMSingh.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_1_4_DSGaur.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_1_5_JMitra.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_1_6_SGurumurthy.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_1_7_RSSMurthy.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_1_8_PRay.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_1_9_BBMishra.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_2_10_JFilliozat.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_2_11_SNSen.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_2_12_RLVerma.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_2_13_PVSharma.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_2_14_HCShukla.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_2_15_TMSrinivasan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_2_1_JCSikdar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_2_2_GNChakravarthy.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_2_3_HCBhardwaj.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_2_4_DPAgrawal.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_2_5_BKGRao.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_2_6_MChoudhury.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_2_7_VGovind.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_2_8_TVMahalingam.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol05_2_9_TMSrinivasan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol07_1_1_RNRai.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol07_1_2_NKPanikkar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol07_1_3_RNRai.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol07_1_4_ALSharma.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol07_1_5_SNSen.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol07_1_6_Notes_AKBag.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol07_1_7_News.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol07_1_8_BookReview.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol07_2_1_RCGupta.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol07_2_2_PVSharma.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol07_2_3_TKBiswas.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol07_2_4_SDSharma.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol07_2_5_VVRaman.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol07_2_6_Notes_VMukherjee.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol07_2_7_BookReviews.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol07_2_8_News.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol09_1_11_DGDhavale.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol09_1_13_RCGupta.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol09_1_14_GSundaramurthy.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol09_1_15_SNSen.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol09_1_16_SMRAnsari.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol09_1_17_MCPande.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol09_1_18_DRKaprekar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol09_1_19_Discussions.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol09_1_6_TSKuppannasastry.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol09_1_7_RNRai.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol09_1_8_BChatterjee.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol09_1_9_CGPendse.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol09_2_1_RCGupta.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol09_2_2_JVNarlikar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol09_2_3_RPKulkarni.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol09_2_4_RCGupta.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol09_2_5_AKMishra.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol09_2_6_VDMarza.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol09_2_7_MNChannabasappa.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol09_2_8_Reviews.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_10_RNRai.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_11_AKBag.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_12_SNSen.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_13_SMRAnsari.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_14_SRoy.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_15_VBMainkar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_16_SMZAlavi.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_17_NKPanikkar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_18_SessionIIDiscussion.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_19_SMAhmad.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_1_WelcomeSpeech_AGJhingran.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_20_BKNayar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_21_SessionIIIDiscussion.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_22_MSAsimov.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_23_AHHabibi.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_24_BKNayar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_25_MRBhat.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_26_SessionIVDiscussion.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_2_IntroductoryRemarks_FCAuluck.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_3_InauguralSpeech_BRSeshachar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_4_MAhmad.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_5_AMShastri.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_6_Ghayasuddin.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_7_BKNayar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_8_SessionIDiscussion.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol10_2_9_BChatterjee.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol13_2_1_SRNMurthy.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol13_2_2_MRoy.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol13_2_3_KNPrasad.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol13_2_4_RPKulkarni.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol13_2_5_RCGupta.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol13_2_6_HGershenowitz.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol13_2_7_TSKShastri.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol13_2_8_BookReviews.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol14_2_10_SSKamavisdar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol14_2_11_BookReviews.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol14_2_12_News.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol14_2_1_SRNMurthy.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol14_2_2_VMukherji.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol14_2_3_HGershenowitz.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol14_2_4_HGershenowitz.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol14_2_5_JCSikdar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol14_2_6_SRNMurthy.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol14_2_7_RSSingh.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol14_2_8_SRNMurthy.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol14_2_9_TSKSastry.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol16_1_10_ABKhan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol16_1_11_SMahdihassan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol16_1_12_NPRai.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol16_1_13_BNSingh.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol16_1_14_AHIsraili.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol16_1_15_AKBose.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol16_1_16_CBDube.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol16_1_1_PVSharma.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol16_1_2_KKThakral.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol16_1_3_RNSingh.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol16_1_4_TSiddiqi.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol16_1_5_TSiddiqi.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol16_1_6_GNChaturvedi.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol16_1_7_SKMishra.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol16_1_8_RSSingh.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol16_1_9_MSKhan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol19_2_10_Report.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol19_2_11_News
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol19_2_1_BDatta.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol19_2_2_HGershenowitz.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol19_2_3_PDGupta.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol19_2_4_MRoy.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol19_2_5_MSBhatnagar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol19_2_6_RMercier.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol19_2_8_VDeshpande.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol19_2_9_BookReviews.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol19_4_10_NotesAndNews
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol19_4_9_BookReviews
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol22_1-12_Announcements.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol22_1_10_BookReviews.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol22_1_11_Report.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol22_1_1_ASRamanathan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol22_1_2_VDeshpande.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol22_1_4_AKBiswas.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol22_1_5_WHAbdi.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol22_1_6_SCKak.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol22_1_7_SMahdihassan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol22_1_8_RKrishnamurthy.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol22_1_9_SChandra.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol22_3_10_Supplement_RasaRatnaSamuccaya.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol22_3_1_ASRamanathan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol22_3_2_ASRamanathan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol22_3_3_ASRamanathan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol22_3_4_SCKak.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol22_3_5_SCKak.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol22_3_6_OPUpadhyay.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol22_3_7_RCGupta.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol22_3_8_Jlaurent.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol22_3_9_BookReviews.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol24_3_10_ProjectsRenewed.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol24_3_1_APKulaichev.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol24_3_2_SAParamhans.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol24_3_4BBLal.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol24_3_5_LCJain.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol24_3_6_SMahadihassan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol24_3_7_RKKochhar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol24_3_8_AKBiswas.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol24_3_9_BookReviews.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol24_4_2_SAParamhans.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol26_1_1_KDAbhyankar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol26_1_2_SMahdihassan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol26_1_3_SRSarma.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol26_1_4_SAParamhans.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol26_1_5_AKChakraborty.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol26_1_6_SSangwan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol26_1_7_ABandyopandhyay.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol26_1_8_BookReview
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol26_4_1_BPrakash.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol26_4_2_SMahdihassan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol26_4_3_NKChandel.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol26_4_4_GAbraham.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol26_4_5_SPGupta.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol26_4_6_SupplementsPanchavimsatika.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol28_1_1_KDAbhyankar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol28_1_2_SCKak.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol28_1_3_PVSharma.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol28_1_4_VNSharma.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol28_1_5_SRSarma.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol28_1_6_SChandra.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol28_1_7_SupplementBibliographyofPhysics.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol28_3_5_News
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol2_2005_01.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol2_2005_02_MANAGEMENT OF FISTULA IN ANO IN ANCIENT GREEK AND AYURVEDIC MEDICINE A HISTORICAL AN.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol2_2005_03_HIPPARCHUS'S 3600 BASED CHORD TABLE AND ITS PLACE IN THE HISTORY OF ANCIENT GREEK AN.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol2_2005_04_HINDUS SCIENTIFIC CONTRIBUTIONS IN INDO CALENDAR.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol2_2005_05_HISTORICAL NOTES_1.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol2_2005_05_HISTORICAL NOTES_2.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol2_2005_06_BOOK REVIEW.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol2_2005_07_NEWS.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol2_2005_08_SUPPLEMENT.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol30_2and3and4_1_APGreeshmalatha.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol30_2and3and4_2_LCJain.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol30_2and3and4_3_MSKhan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol30_2and3and4_4_AKChakravarty.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol30_2and3and4_5_BookReviews.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol30_2and3and4_6_News.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol30_2and3and4_7_Supplementary_HistoryofMagneticStudiesinIndia.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol31_1_1_AKChakravarty.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol31_1_2_KDAbhyankar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol31_1_3_AMShastri_vikrama.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol31_1_4_AMShastri_Saka.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol31_1_5_ABhattacharyya.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol31_1_6_KVSarma.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol31_1_7_NewsSeminarPublications.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol31_1_8_SupplementBibliographyon MagneticStudies.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol31_3_1_HWLaale.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol31_3_2_MBanerjee.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol31_3_3_SDSharma.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol31_3_4_VDeshpande.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol31_3_5_PKMisra.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol31_3_6_BookReviewandNews.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol32_1_10_SupplementRasahrdayatantramCh1to10
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol32_1_1_BPrakash.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol32_1_2_GVRajamanickam.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol32_1_3_GAbraham.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol32_1_4_AMukhopadhyay.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol32_1_5_SKChatterjee.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol32_1_6_BNMukherjee.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol32_1_7_BookReview.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol32_1_9_NewsandAcademyPublicationsonHOS
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol33_3_1_SCKak.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol33_3_2_KCHari.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol33_3_3_CSRao.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol33_3_4_NGDongre.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol33_3_5_ADas.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol33_3_6_AcademyPublicationsofHOS.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol33_3_7_Supplement.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol34_1_1_KCHari.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol34_1_2_NKumar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol34_1_3_RShrivastva.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol34_1_4_AGhosh.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol34_1_5_RSingh.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol34_1_6_BookReviews.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol34_1_7_News.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol34_3_1_RShrivastva.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol34_3_2_RNIyengar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol34_3_3_NKMaitra.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol34_3_4_BookReviews.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol34_3_5_News.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol35_4_1_BNNAchar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol35_4_2_HThurston.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol35_4_3_DRaina.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol35_4_4_BookReviews.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol35_4_5_SupplementsHOSResearchProjects.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol36_1and2_1_RBalasubramanian.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol36_1and2_2_SRSarma.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol36_1and2_3_AKBag.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol36_1and2_4_BookReview.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol36_1and2_5_Notices.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol36_1and2_6_Conferences.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol36_1and2_7_Projects.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol36_3and4_1_BSasisekaran.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol36_3and4_2_KVSarma.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol36_3and4_3_YVJeppu.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol36_3and4_4_KCHari.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol36_3and4_5_GSSodhi.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol36_3and4_6_BookReviews.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol36_3and4_7_ProjectReport.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol36_3and4_8_Conferences.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol37_1_1_RBalasubramaniam.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol37_1_2_BSasisekaran.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol37_1_3_KDAbhyankar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol37_1_4_VJha.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol37_1_5_TVVenkateswaran.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol37_1_6_BookReview.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol37_1_7_Conference.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol37_1_9_Supplement ScientificPeriodicals.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol37_2_10_INCforHOS.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol37_2_11_SupplementScientificPeriodicals.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol37_2_1_BNNAchar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol37_2_2_KCHari.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol37_2_3_RBalasubramaniam.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol37_2_4_JWisniak.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol37_2_5_RSingh.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol37_2_6_BookReview.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol37_2_7_ProjectReport.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol37_2_8_Conferences.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol37_2_9_BChaki.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol39_2_1_SKAcharya.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol39_2_2_KCHari.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol39_2_3_RBalasubramaniam.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol39_2_4_NAthiyaman.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol39_2_5_HistoricalNotes.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol39_2_6_NRathnasree.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol39_2_7_BookReviews.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol39_2_8_Notices.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol39_2_9_Supplement.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol41_1_7_Einstien.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_1_10_Supplement.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_1_1_RKDubey.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_1_2_JKozhmthadan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_1_3_DRaina.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_1_4_SSahoo.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_1_5_BSahai.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_1_6_HJoglekar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_1_7_NRatnasree.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_1_8_BSShyalaja.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_1_9_BookReview.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_3_10_SJaikishan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_3_11_RBalasubramaniam.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_3_12_HistoricalNoteRBalasubramaniam.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_3_13_HistoricalNoteGJuleff.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_3_14_HistoricalNoteLPandey.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_3_15_Historical NoteRBalasubramaniam.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_3_1_DBWagner.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_3_2_AFeuerbach.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_3_3_JLCoze.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_3_4_AFeuerbach.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_3_5_PKChattopadhyay.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_3_6_VTripathi.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_3_7_RBalasubramaniam.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_3_8_SJaikishan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_3_9_SJaikishan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_4_10_SJaikishan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_4_11_BookReview.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_4_12_Supplement.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_4_1_JWadsworth.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_4_2_JVerhoeven.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_4_3_JLCoze.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_4_4_PTCraddock.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_4_5_VKumar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_4_6_MRBarnett.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_4_7_RBalasubramaniam.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_4_8_SSrinivasan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol42_4_9_HistoricalNotes.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol43_4_10_BooksreceivedforReview.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol43_4_1_PGondhalekar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol43_4_2_Sbalachandrarao.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol43_4_3_VMMallayya.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol43_4_4_SDucheyne.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol43_4_5_HSingh.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol43_4_6_SKMajumdar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol43_4_7_BookReviewKRajan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol43_4_8_BookReviewBPrakash.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol43_4_9_News.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_11_SupplementRasaprakasasudhakara.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_2_0_Editorial.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_2_10_SPrema.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_2_11_RSarkar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_2_12_SDas.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_2_13_Supplement.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_2_1_CPechhia.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_2_2_PAMaas.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_2_3_DWujastyk.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_2_4_KGZysk.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_2_5_PT Craddock.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_2_6_ACerulli.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_2_7_MSankaranarayana.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_2_8_KPrasendanz.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_2_9_HistoricalNotes.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_3_10_SShuklapdf.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_3_1_RNIyengar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_3_2_WLox.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_3_3_RBalasubramaniampdf.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_3_4_KRoy.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_3_5_Historical Notes.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_3_6_RBhattacharya.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_3_7_AKBag.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_3_8_AKBiswaspdf.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol44_3_9_News.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol45_3_0_Contents.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol45_3_10_NParthasar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol45_3_11_News.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol45_3_12_SupplementInn.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol45_3_13_Sanskrittextc.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol45_3_14_EnglishtextCha.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol45_3_1_PGondalekha.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol45_3_2_MNVahia.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol45_3_3_BSasisekara.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol45_3_4_RKDubey.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol45_3_5_JLCoze.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol45_3_6_SRSarma.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol45_3_7_HSingh.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol45_3_8_SKSen.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol45_3_9_NupurDasgup.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_1_5_JBhattacharyya.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_2_0_Contents.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_2_10_AKThakur.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_2_11_SuktaDas.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_2_12_NewsSRSarma.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_2_13_NewsKnudsen.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_2_14_NewsShukla.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_2_15_Supplement.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_2_1_KJaouiche.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_2_2_AKeller.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_2_3_DRaina.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_2_4_1_MJDurandRichard.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_2_7_SKMajumdar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_2_8_BShailaja.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_2_9_Bookreview.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_2_9_Bookreview.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_3_10_News.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_3_11_Supplement.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_3_12_Supplement.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_3_1_BPrakash.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_3_2_ANarayanan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_3_3_AKBiswas.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_3_4_SNBiswas.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_3_5_RCGupta.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_3_6_SKMajumdar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_3_7_Bookreview.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol46_3_8_SVSingh.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol47_3_4(1)_PKBandyopadhyay.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol47_4_0_Editorial.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol47_4_10_Malaya.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol47_4_11_PPDivakaran.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol47_4_12_Booksreceived.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol47_4_13_Cumulativeindex.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol47_4_14_Annualcontent.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol47_4_1_Contents.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol47_4_2_PRamManohar.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol47_4_3_DPKaundinya.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol47_4_4_RSridhan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol47_4_5_RSridhan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol47_4_6_ADutta.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol47_4_7_AKBag.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol47_4_8_SMadhavan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol47_4_9_MSSriram.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol48_4_10_ProjectReport_ BKSen
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol48_4_11_ News
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol48_4_12_BookReceivedForReview
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol48_4_13_CumulativeIndex
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol48_4_14_AnnualContent
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol48_4_3_ AMSharan.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol48_4_6_ RCGupta
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol48_4_8_Book Review
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol48_4_9_Project Report_ Jbhattacharyya
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol49_1_1_PKChattopadhyay.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol4_2005_01_IRON CANNONS OF CHINA.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol4_2005_02_MONSTER CANNON WROUGHT IRON BOMBARDS OF EUROPE.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol4_2005_03_CANNONS OF EASTERN INDIA.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol4_2005_04_FORGE WELDED CANNONS IN THE FORTS OF KARIMNAGAR DISTRICT IN THE ANDHRA PRADESH.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol4_2005_05_DEVELOPMENT OF CANNON TECHNOLOGY IN INDIA.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol4_2005_06_EPIC OF SALTPETRE TO GUNPOWDER.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol4_2005_07_GUNPOWDER ARTILLERY AND MILITARY ARCHITECTURE IN SOUTH INDIA (15-18TH CENTURY).pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol4_2005_08_FIREPOWER CENTRIC WARFARE IN INDIA AND MILITARY MODERNIZATION OF THE MARATHAS 1740-1.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol4_2005_09_ROCKETS UNDER HAIDAR ALI AND TIPU SULTAN'.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol4_2005_10_HISTORICAL NOTES_2.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol4_2005_10_HISTORICAL NOTES_3.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol4_2005_11_BOOK REVIEW.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol4_2005_12_NEWS.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol4_2005_13_SUUPPLEMENT.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol50_2015_2_Art01.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol50_2015_2_Art02.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol50_2015_2_Art03.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol50_2015_2_Art04.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol50_2015_2_Art05.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol50_2015_2_Art06.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol50_2015_2_Art07.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol50_2015_2_Art08.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol50_2015_2_Art09.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol50_2015_2_Art10.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol50_2015_2_Art11.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol50_2015_2_Art12.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol50_2015_2_Art13.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol50_2015_2_Art14.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol50_2015_2_Art15.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol50_2015_2_Contents.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol52_3_2017__Art01.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol52_3_2017__Art02.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol52_3_2017__Art03.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol52_3_2017__Art04.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol52_3_2017__Art05.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol52_3_2017__Art06.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol52_3_2017__Art07.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol52_3_2017__Art08.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol52_3_2017__Art09.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol52_3_2017__Art10.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol52_3_2017__Art11.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol52_3_2017__Art12.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_3_2018__Art01.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_3_2018__Art02.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_3_2018__Art03.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_3_2018__Art04.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_3_2018__Art05.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_3_2018__Art06.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_3_2018__Art07.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_3_2018__Art08.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_3_2018__Art09.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_3_2018__Art10.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_3_2018__Art11.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_3_2018__Art12.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_3_2018__Art13.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018-Cumulativeindex.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018-Index.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art01.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art02.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art03.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art04.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art05.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art06.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art07.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art08.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art09.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art10.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art11.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art12.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art13.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art14.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art15.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art16.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art17.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art18.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art19.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art20.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art21.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art22.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art23.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art24.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art25.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art26.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art27.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art28.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art29.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art30.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art31.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Art32.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Books.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol53_4_2018__Contents.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol9_1_1_EKKharadze.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol9_1_2_JSmak.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol9_1_3_ATrautman.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol9_1_4_SCJoshi.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol9_1_5_SKGhosh.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol9_1_6_TSKuppannasastry.pdf
wget -N https://insa.nic.in//writereaddata/UpLoadedFiles/IJHS/Vol_16_1_0_Address.pdf
